- hosts: s3.infra
  become: true
  vars:
    mariadb_root_password: "projet"
  tasks:
    - name: Install python3-pymysql
      apt:
        name: python3-pymysql
        state: present
        force: yes

    - name: Install MariaDB
      apt:
        name: mariadb-server
        state: present

    - name: Start MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Configure MariaDB root password
      lineinfile:
        path: /etc/mysql/debian.cnf
        regexp: "^\\[mysqld\\]$"
        line: |
          [mysqld]
          root_password={{ mariadb_root_password }}

    - name: Create a test database
      mysql_db:
        name: test
        state: present

    - name: Grant all privileges on the test database to the root user
      mysql_user:
        name: root
        host: '%'
        password: "{{ mariadb_root_password }}"
        priv: "*.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mariadb_root_password }}"

    - name: Restart MariaDB
      service:
        name: mariadb
        state: restarted

