---
- hosts: s3.infra
  become: true
  vars:
    mariadb_host: "138.68.93.114"
    mariadb_root_username: "projet"
    mariadb_root_password: "projet"
  tasks:
    - name: Install python3-pymysql
      apt:
        name: python3-pymysql
        state: present
        force: yes

    - name: Install MariaDB
      apt:
        name: mariadb-server
        state: present

    - name: Start MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

#    - name: Configure MariaDB root password
 #     lineinfile:
  #      path: /etc/mysql/debian.cnf
   #     regexp: "^\\[mysqld\\]$"
    #    line: |
     #     [mysqld]
      #    root_password={{ mariadb_root_password }}

    - name: Create a test database
      mysql_db:
        name: test
        login_host: "{{ mariadb_host }}" 
        login_user: "{{ mariadb_root_username }}"
        login_password: "{{ mariadb_root_password }}"
        state: present

#    - name: Restart MariaDB
  #    service:
    #    name: mariadb
      #  state: restarted

