---
- name: Mount NFS Share on s1.infra and s2.infra
  hosts: s1.infra:s2.infra
  become: true

  tasks:
    - name: Install NFS Client package
      apt:
        name: nfs-common
        state: present

    - name: Create mount point directory
      file:
        path: /mnt/nfs
        state: directory
        mode: "0755"

    - name: Mount NFS Share
      mount:
        path: /mnt/nfs
        src: "167.71.51.134:/home/data"
        fstype: nfs
        state: mounted
        opts: "defaults"