---
- name: Install and configure WordPress on web servers
  hosts: s1.infra,s2.infra
  become: yes
  vars:
    wordpress_domains:
      - devops.com
      - devsec.com
      - devsecops.com
    mynfs: 167.71.51.134:/wordpress
    myopts: "rw,sync"

  tasks:
    - name: Install Apache web server
      package:
        name: apache2
        state: present

    - name: Enable Apache mod_rewrite
      apache2_module:
        name: rewrite
        state: present

    - name: Install PHP and required modules
      package:
        name: "{{ item }}"
        state: present
      loop:
        - libapache2-mod-php
        - php
        - php-mysql
        - php-gd
        - php-curl

    - name: Restart Apache service
      service:
        name: apache2
        state: restarted

    - name: Download WordPress archive
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: /tmp/wordpress.tar.gz

    - name: Create sites directories
      file:
        path: "/var/www/{{ item.domain }}"
        state: directory
      with_items:
        - { domain: "{{ wordpress_domains[0] }}" }
        - { domain: "{{ wordpress_domains[1] }}" }
        - { domain: "{{ wordpress_domains[2] }}" }

    - name : mount /mnt/devops
      ansible.posix.mount:
        src : "{{ mynfs }}/devops"
        path : "/var/www/devops.com/"
        fstype : nfs
        opts : "{{ myopts }}"
        state : mounted

    - name : mount /mnt/devsec
      ansible.posix.mount:
        src : "{{ mynfs }}/devsec"
        path : "/var/www/devsec.com/"
        fstype : nfs
        opts : "{{ myopts }}"
        state : mounted

    - name : mount /mnt/devsecops
      ansible.posix.mount:
        src : "{{ mynfs }}/devsecops"
        path : "/var/www/devsecops.com/"
        fstype : nfs
        opts : "{{ myopts }}"
        state : mounted

    - name: Extract WordPress archive
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: "/tmp"
        remote_src: yes

    - name: Copy WordPress archive
      copy:
        src: /tmp/wordpress
        dest: "/var/www/{{ item.domain }}/"
        remote_src: yes
      with_items:
        - { domain: "{{ wordpress_domains[0] }}" }
        - { domain: "{{ wordpress_domains[1] }}" }
        - { domain: "{{ wordpress_domains[2] }}" }

    - name: Create virtual host configurations
      template:
        src: 000-default.conf.j2
        dest: "/etc/apache2/sites-available/{{ item.domain }}.conf"
      with_items:
        - { domain: "{{ wordpress_domains[0] }}" }
        - { domain: "{{ wordpress_domains[1] }}" }
        - { domain: "{{ wordpress_domains[2] }}" }

    - name: Configure virtual hosts
      lineinfile:
        path: "/etc/apache2/sites-available/{{ item.domain }}.conf"
        regexp: "^<VirtualHost .*:80>"
        line: "<VirtualHost *:80>"
      with_items:
        - { domain: "{{ wordpress_domains[0] }}" }
        - { domain: "{{ wordpress_domains[1] }}" }
        - { domain: "{{ wordpress_domains[2] }}" }
      notify:
        - Restart Apache

    - name: Enable virtual hosts
      command: a2ensite {{ item.domain }}
      with_items:
        - { domain: "{{ wordpress_domains[0] }}" }
        - { domain: "{{ wordpress_domains[1] }}" }
        - { domain: "{{ wordpress_domains[2] }}" }
      notify:
        - Restart Apache

    - name: Disable default virtual host
      command: a2dissite 000-default
      ignore_errors: yes
      notify:
        - Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted