- hosts: s0.infra
  become: true
  tasks:
    - name: Install DHCP server
      apt:
        name: isc-dhcp-server
        state: present

    - name: Configure DHCP server
      lineinfile:
        path: /etc/dhcp/dhcpd.conf
        insertafter: "subnet 192.168.50.0 netmask 255.255.255.0 {"
        line: |
          pool {
            range 192.168.50.10 192.168.50.254;
            deny unknown-clients;
          }
        state: present

    - name: Configure hosts
      lineinfile:
        path: /etc/dhcp/dhcpd.conf
        insertafter: "deny unknown-clients;"
        line: |
          host s1.infra {
            hardware ethernet da:25:66:53:cb:75;  
            fixed-address 192.168.50.10;
          }
          host s2.infra {
            hardware ethernet 8a:de:60:de:b4:4f;  
            fixed-address 192.168.50.11;
          }
          host s3.infra {
            hardware ethernet be:43:bb:8c:e4:27;
            fixed-address 192.168.50.12;
          }
          host s4.infra {
            hardware ethernet a6:f3:e2:b6:89:2c;
            fixed-address 192.168.50.13;
          }
        state: present

    - name: Start DHCP service
      service:
        name: isc-dhcp-server
        state: started
        enabled: yes

