---
- name: Install NFS Server on s4.infra
  hosts: s4.infra
  become: true

  tasks:
    - name: Install NFS Server package
      apt:
        name: nfs-kernel-server
        state: present

    - name: Create shared directory
      file:
        path: /home/data
        state: directory
        mode: "0755"

    - name: Configure NFS exports
      lineinfile:
        path: /etc/exports
        line: "/home/data *(rw,sync,no_root_squash,no_subtree_check)"
        state: present
      notify:
        - Restart NFS Server

  handlers:
    - name: Restart NFS Server
      service:
        name: nfs-kernel-server
        state: restarted
