---
- hosts: s3.infra
  become: true
  vars:
    mariadb_host: "138.68.93.114"
    mariadb_username: "wp_user"
    mariadb_password: "wp_projet"
    mariadb_db: "wordpress"
  tasks:
    - name: Install python3-pymysql
      apt:
        name: python3-pymysql
        state: present
        force: yes

    - name: Install MariaDB
      apt:
        name: mariadb-server
        state: present

    - name: Start MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create MariaDB user
      shell: >
        mysql -e "CREATE USER '{{mariadb_username}}'@'%' IDENTIFIED BY '{{mariadb_password}}';" && mysql -e "GRANT ALL PRIVILEGES ON *.* TO '{{ mariadb_username }}'@'%';"
      register: create_user_result
      ignore_errors: yes

    - name: Create a test database
      mysql_db:
        name: "{{ mariadb_db }}"
        login_host: "{{ mariadb_host }}" 
        login_user: "{{ mariadb_username }}"
        login_password: "{{ mariadb_password }}"
        state: present

#    - name: Restart MariaDB
  #    service:
    #    name: mariadb
      #  state: restarted

