---
- hosts: s3.infra
  become: true
  vars_files:
    - secret.yml
  tasks:
    - name: Install python3-pymysql
      apt:
        name: python3-pymysql
        state: present
        force: yes

    - name: Install MariaDB
      apt:
        name: mariadb-server
        state: present

    - name: Start MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create MariaDB user
      shell: >
        mysql -e "CREATE USER '{{wordpress_db_user}}'@'%' IDENTIFIED BY '{{wordpress_db_password}}';" && mysql -e "GRANT ALL PRIVILEGES ON *.* TO '{{ wordpress_db_user }}'@'%';"
      register: create_user_result
      ignore_errors: yes

    - name: Create devops db 
      mysql_db:
        name: "{{ devops_db }}"
        login_host: "{{ db_host }}" 
        login_user: "{{ wordpress_db_user }}"
        login_password: "{{ wordpress_db_password }}"
        state: present

    - name: Create devsec db
      mysql_db:
        name: "{{ devsec_db }}"
        login_host: "{{ db_host }}"     
        login_user: "{{ wordpress_db_user }}"
        login_password: "{{ wordpress_db_password }}"
        state: present

    - name: Create devsecops db
      mysql_db:
        name: "{{ devsecops_db }}"
        login_host: "{{ db_host }}"       
        login_user: "{{ wordpress_db_user }}"
        login_password: "{{ wordpress_db_password }}"
        state: present
